package app

import (
	"errors"
	"fmt"

	"charm.land/bubbletea/v2"
	"github.com/larkly/lazystack/internal/audit"
	"github.com/larkly/lazystack/internal/compute"
	"github.com/larkly/lazystack/internal/shared"
	"github.com/larkly/lazystack/internal/ui/serveradminact"
	"github.com/larkly/lazystack/internal/ui/vmpassword"
)

// actionWarningMsg reports an action result together with a partial-result
// warning (the action succeeded, but part of its outcome is unavailable).
type actionWarningMsg struct {
	result  tea.Msg
	warning string
}

func (m Model) handleActionWarning(msg actionWarningMsg) (Model, tea.Cmd) {
	var cmd tea.Cmd
	if msg.result != nil {
		var next tea.Model
		next, cmd = m.Update(msg.result)
		m = next.(Model)
	}
	m.statusBar.StickyHint = fmt.Sprintf("%s  ⚠ %s", m.statusBar.StickyHint, msg.warning)
	return m, cmd
}

// executeAdminAction runs an admin action requested by the admin modal with
// a request deadline, the server's in-flight lock and a per-target audit
// record. Results are reported by the root, so they stay visible after the
// modal has closed.
func (m Model) executeAdminAction(req serveradminact.ActionRequestMsg) (Model, tea.Cmd) {
	var auditAction audit.ActionType
	var details map[string]string
	switch req.Action {
	case "Migrate":
		auditAction = audit.ActionMigrate
	case "Live Migrate":
		auditAction = audit.ActionLiveMigrate
		details = map[string]string{"host": req.Arg}
	case "Evacuate":
		auditAction = audit.ActionEvacuate
		if req.Arg != "" {
			details = map[string]string{"host": req.Arg}
		}
	case "Force Delete":
		auditAction = audit.ActionForceDelete
	case "Reset State":
		auditAction = audit.ActionResetState
		details = map[string]string{"state": req.Arg}
	default:
		return m, nil
	}
	if req.ServerID == "" || m.client == nil {
		return m, nil
	}
	locks := []actionLock{m.lock("server", req.ServerID, req.ServerName)}
	if busy := m.busy(locks); busy != "" {
		return m.rejectBusy(busy)
	}
	client := m.client.Compute
	id, name, arg := req.ServerID, req.ServerName, req.Arg
	cmd := func() tea.Msg {
		ctx, cancel := actionCtx()
		defer cancel()
		shared.Debugf("[action] admin %s on server %s", req.Action, id)
		var err error
		var adminPass string
		switch req.Action {
		case "Migrate":
			err = compute.MigrateServer(ctx, client, id)
		case "Live Migrate":
			err = compute.LiveMigrateServer(ctx, client, id, arg)
		case "Evacuate":
			adminPass, err = compute.EvacuateServer(ctx, client, id, arg, false)
		case "Force Delete":
			err = compute.ForceDeleteServer(ctx, client, id)
		case "Reset State":
			err = compute.ResetServerState(ctx, client, id, arg)
		}
		var warning string
		if errors.Is(err, compute.ErrAdminPassUnreadable) {
			// The evacuation was accepted; only its password is missing.
			// Report it as a partial result and never retry the action.
			warning = "evacuated, but the new admin password could not be read"
			shared.Debugf("[action] admin evacuate %s: %v", id, err)
			err = nil
		}
		if err != nil {
			shared.Debugf("[action] admin %s on %s failed: %v", req.Action, id, err)
			m.logAuditDetails(auditAction, "server", id, name, "error", err.Error(), details)
			return shared.ServerActionErrMsg{Action: req.Action, Name: name, Err: err}
		}
		m.logAuditDetails(auditAction, "server", id, name, "success", "", details)
		if req.Action == "Force Delete" {
			return serverDeletedMsg{id: id, name: name}
		}
		var result tea.Msg = shared.ServerActionMsg{Action: req.Action, Name: name}
		if adminPass != "" {
			result = credentialsMsg{
				result: result,
				title:  "Evacuation Password",
				note:   "New admin password generated by the evacuation; it is not stored anywhere.",
				creds:  []vmpassword.Credential{{Server: name, Secret: adminPass}},
			}
		}
		if warning != "" {
			result = actionWarningMsg{result: result, warning: warning}
		}
		return result
	}
	next, tracked, _ := m.trackAction(locks, cmd)
	return next, tracked
}
